# Form implementation generated from reading ui file 'D:\TDLT\ThucHanh\End-term_Project\Main\GiaoDien_Table\ChatAI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(500, 650)
        ChatWindow.setStyleSheet("background-color: #CFEBFC; font-family: \'Times New Roman\'; font-size: 14px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(ChatWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_display = QtWidgets.QTextBrowser(parent=ChatWindow)
        self.chat_display.setStyleSheet("QTextBrowser {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    font-size: 15px;\n"
"    border: 1px solid #A0C4FF;\n"
"}")
        self.chat_display.setObjectName("chat_display")
        self.verticalLayout.addWidget(self.chat_display)
        self.input_layout = QtWidgets.QHBoxLayout()
        self.input_layout.setObjectName("input_layout")
        self.input_field = QtWidgets.QLineEdit(parent=ChatWindow)
        self.input_field.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"    padding: 10px 15px;\n"
"    font-size: 14px;\n"
"    border: 1px solid #A0C4FF;\n"
"}")
        self.input_field.setObjectName("input_field")
        self.input_layout.addWidget(self.input_field)
        self.btn_send = QtWidgets.QPushButton(parent=ChatWindow)
        self.btn_send.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_send.setStyleSheet("QPushButton {\n"
"    background-color: #2196F3;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #0b7dda; }")
        self.btn_send.setObjectName("btn_send")
        self.input_layout.addWidget(self.btn_send)
        self.verticalLayout.addLayout(self.input_layout)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "Trợ lý AI - Quản lý Sinh Viên"))
        self.input_field.setPlaceholderText(_translate("ChatWindow", "Nhập câu hỏi của bạn vào đây..."))
        self.btn_send.setText(_translate("ChatWindow", "Gửi"))
